language: perl
perl:
   - 5.19
   - 5.18
   - 5.16
   - 5.14
   - 5.12
   - 5.10
   - 5.8
matrix:
   allow_failures:
      - perl: 5.8
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - rm .travis.yml
   - cpanm --quiet --notest --skip-satisfied autovivification indirect multidimensional
install:
   - cpanm --installdeps --verbose  .
notifications:
   irc:
      channels:
         - irc.perl.org#sanity
      on_failure: always
      on_success: change
      template:
         - '%{branch}#%{build_number} by %{author}: %{message} (%{build_url})'
      use_notice: true
